runtime: python39
entrypoint: gunicorn -b :$PORT main:app

# Add any environment variables your application needs here.
# env_variables:
#   KEY: "value"

# Automatic scaling settings (adjust as needed).
automatic_scaling:
  target_cpu_utilization: 0.65
  target_memory_utilization: 0.65

# You may need to specify additional settings depending on your application.

# handlers:
# - url: /static
#   static_dir: static/

# - url: /.*
#   script: auto
