# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Asia/Shanghai

# jekyll-seo-tag settings
title: Chirpy
tagline: A text-focused Jekyll theme
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# Fill in the protocol & hostname for your site.
url: "https://your-website.com"

github:
  username: your-github-username

twitter:
  username: your-twitter-username

social:
  name: Your Full Name
  email: your.email@example.com
  links:
    - https://twitter.com/your-twitter-username
    - https://github.com/your-github-username

google_site_verification: your-verification-string

# jekyll-seo-tag settings end

google_analytics:
  id: your-google-analytics-id

# Prefer color scheme setting.
theme_mode: # [light|dark]

# The CDN endpoint for images.
img_cdn: "https://your-cdn-endpoint.com"

# the avatar on sidebar, support local or CORS resources
avatar: "/commons/avatar.jpg"

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  active: disqus
  disqus:
    shortname: your-disqus-shortname

# utterances settings
utterances:
  repo: your-github-username/your-repo
  issue_term: url

# Giscus options
giscus:
  repo: your-github-username/your-repo
  repo_id: your-repo-id
  category: your-category
  category_id: your-category-id
  mapping: pathname
  input_position: bottom
  lang: en
  reactions_enabled: 1

# Self-hosted static assets, optional
assets:
  self_host:
    enabled: false

# the option for PWA feature
pwa:
  enabled: true

paginate: 10

# The base URL of your site
baseurl: ""

# The following options are not recommended to be modified
# ... (remaining configuration options)

